---
name: Run Rancher2 Airgap Test Suite
description: "Runs rancher2 airgap test suite"

inputs:
  suite:
    description: "The specific Rancher2 suite to run on the specific Rancher server"
    required: false
  package:
    description: "Package to test"
    required: true
  timeout:
    description: "Timeout"
    required: true
  reporting:
    description: "Enable reporting"
    required: false
    default: "false"
    
runs:
  using: composite
  steps:
    - name: Run Tests
      id: tests
      run: |
        set +e
        
        gotestsum --format standard-verbose --packages=github.com/rancher/tfp-automation/tests/${{ inputs.package }}/airgap \
          --junitfile results.xml --jsonfile results_airgap.json -- -timeout=${{ inputs.timeout }} -tags=recurring -v;
          airgap_code=$?;
          echo "airgap_code=$airgap_code" >> $GITHUB_ENV;
          cp results_airgap.json results.json

          if [[ "${{ inputs.reporting }}" == "true" ]]; then
            ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
            ./validation/reporter;
          fi
      shell: bash
      continue-on-error: true

    - name: Show failed tests
      run: |
         declare -A suites=(
           [airgap_code]="Airgap:results_airgap.json"
         )

         failed=0
         for exit_code in "${!suites[@]}"; do
          IFS=: read suite_name results_file <<< "${suites[$exit_code]}"
          exit_val="${!exit_code}"

          if [ "$exit_val" != "" ] && [ "$exit_val" -ne 0 ]; then
            echo "Failed $suite_name tests:"
            jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' "$results_file"
            failed=1
          fi
         done

         if [ "$failed" -eq 1 ]; then
          exit 1
         fi
      shell: bash