---
name: KDM Testing

on:
  workflow_dispatch:
    inputs:
      rancher_version:
        description: "Rancher version"
      rancher_chart_version:
        description: "Rancher chart version"
  workflow_call:
    inputs:
      rancher_version:
        description: "Rancher tag version"
        type: string
        required: true
      rancher_chart_version:
        description: "Rancher chart version"
        type: string
        required: true

permissions:
  id-token: write
  contents: read

env:
  CLOUD_PROVIDER_VERSION: "5.95.0"
  HOSTNAME_PREFIX: "tfp-kdm"
  LOCALS_PROVIDER_VERSION: "${{ vars.LOCALS_PROVIDER_VERSION }}"
  PACKAGE: "kdm"
  RKE_PROVIDER_VERSION: "${{ vars.RKE_PROVIDER_VERSION }}"
  TEST_SUITE: "^TestKDMTestSuite$"
  TIMEOUT: "5h"

jobs:
  kdm-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: head
            environment: latest
            provider_version: ${{ vars.RANCHER2_PROVIDER_VERSION_2_13 }}
            rancher_prefix_version: "head"
            rke2_version: ${{ vars.RKE2_VERSION_2_12 }}
            rancher_chart_version: "${{ vars.RELEASED_RANCHER_CHART_VERSION_2_12 }}"
            rancher_version: "${{ vars.RANCHER_VERSION_HEAD }}"
            qase_rc_id: ${{ vars.QASE_RC_TEST_RUN_ID_2_13 }}
            qase_id: ${{ vars.QASE_RECURRING_TEST_RUN_ID_2_13 }}

          - version: v2-12
            environment: latest
            provider_version: ${{ vars.RANCHER2_PROVIDER_VERSION_2_12 }}
            rancher_prefix_version: "v2.12"
            rke2_version: ${{ vars.RKE2_VERSION_2_12 }}
            rancher_chart_version: "${{ vars.RELEASED_RANCHER_CHART_VERSION_2_12 }}"
            rancher_version: "${{ vars.RANCHER_VERSION_2_12_HEAD }}"
            qase_rc_id: ${{ vars.QASE_RC_TEST_RUN_ID_2_12 }}
            qase_id: ${{ vars.QASE_RECURRING_TEST_RUN_ID_2_12 }}

          - version: v2-11
            environment: staging
            provider_version: ${{ vars.RANCHER2_PROVIDER_VERSION_2_11 }}
            rancher_prefix_version: "v2.11"
            rke2_version: ${{ vars.RKE2_VERSION_2_11 }}
            rancher_chart_version: "${{ vars.RELEASED_RANCHER_CHART_VERSION_2_11 }}"
            rancher_version: "${{ vars.RANCHER_VERSION_2_11_HEAD }}"
            qase_rc_id: ${{ vars.QASE_RC_TEST_RUN_ID_2_11 }}
            qase_id: ${{ vars.QASE_RECURRING_TEST_RUN_ID_2_11 }}
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    env:
      RANCHER2_PROVIDER_VERSION: ${{ matrix.provider_version }}

    steps:
      - name: Skip non-matching matrix versions
        id: skip-matrix-version
        if: |
          github.event_name == 'schedule' ||
          github.event.inputs.run_all_versions == 'true' ||
          (github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.rancher_version, matrix.rancher_prefix_version)) && contains(github.event.inputs.rancher_version, '-alpha')
        run: |
          INPUT_VERSION="${{ github.event.inputs.rancher_version }}"
          MATRIX_VERSION="${{ matrix.version }}"
          MATRIX_VERSION="${MATRIX_VERSION//-/.}"
          EVENT_NAME="${{ github.event_name }}"

          echo "INPUT_VERSION=$INPUT_VERSION"
          echo "MATRIX_VERSION=$MATRIX_VERSION"
          if [[ "${{ github.event.inputs.run_all_versions }}" == "true" || \
                "$EVENT_NAME" == "schedule" || \
                ("$EVENT_NAME" == "workflow_dispatch" && "$INPUT_VERSION" == "$MATRIX_VERSION"*) || \
                ("$EVENT_NAME" == "workflow_call" && "$INPUT_VERSION" == "$MATRIX_VERSION"*) ]]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
            echo "Skipping version ${{ matrix.version }}"
            exit 0
          fi
      
      - name: Checkout repository
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up environment variables
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        run: |
          if [ "${{ matrix.environment }}" == "latest" ]; then
            echo "PREFIX_LIST_ID=${{ secrets.AWS_MANAGED_PREFIX_LIST_ID }}" >> $GITHUB_ENV
            echo "SECURITY_GROUPS=${{ secrets.AWS_SECURITY_GROUPS }}" >> $GITHUB_ENV
            echo "SECURITY_GROUP_NAMES=${{ secrets.AWS_SECURITY_GROUP_NAMES }}" >> $GITHUB_ENV
            echo "RANCHER_AGENT_IMAGE=" >> $GITHUB_ENV
          elif [ "${{ matrix.environment }}" == "staging" ]; then
            echo "PREFIX_LIST_ID=${{ secrets.AWS_MANAGED_PREFIX_LIST_ID_PRIME }}" >> $GITHUB_ENV
            echo "SECURITY_GROUPS=${{ secrets.AWS_SECURITY_GROUPS_PRIME }}" >> $GITHUB_ENV
            echo "SECURITY_GROUP_NAMES=${{ secrets.AWS_SECURITY_GROUP_NAMES_PRIME }}" >> $GITHUB_ENV
            echo "RANCHER_AGENT_IMAGE=${{ secrets.RANCHER_AGENT_IMAGE }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS credentials from Secrets Manager
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            AWS_ACCESS_KEY, ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_KEY, ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Fetch and Set DockerHub Credentials"
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials username | DOCKERHUB_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials password | DOCKERHUB_PASSWORD

      - name: Mask Dockerhub Credentials
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        run: |
          echo "::add-mask::${{ env.DOCKERHUB_USERNAME }}"
          echo "::add-mask::${{ env.DOCKERHUB_PASSWORD }}"

      - name: Whitelist Runner IP
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: ./.github/actions/whitelist-runner-ip
        with:
          prefix-list-id: ${{ env.PREFIX_LIST_ID }}
          region: "${{ secrets.AWS_REGION }}"

      - name: Set up SSH Keys
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: ./.github/actions/setup-ssh-keys
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-private-key-name: ${{ secrets.SSH_PRIVATE_KEY_NAME }}
          windows-ssh-private-key: ${{ secrets.WINDOWS_SSH_PRIVATE_KEY }}
          windows-ssh-private-key-name: ${{ secrets.WINDOWS_SSH_PRIVATE_KEY_NAME }}

      - name: Uniquify hostname prefix
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: ./.github/actions/uniquify-hostname

      - name: Set Rancher version
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_VERSION
          value: |
            ${{ 
              github.event.inputs.rancher_version || 
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_version) ||
              (github.event.inputs.run_all_versions == 'true' && github.event.inputs.rancher_version)
            }}

      - name: Set Rancher chart version
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_CHART_VERSION
          value: |
            ${{ 
              github.event.inputs.rancher_chart_version || 
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_chart_version) ||
              (github.event.inputs.run_all_versions == 'true' && matrix.rancher_chart_version)
            }}

      - name: Set Rancher repo
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: ./.github/actions/set-rancher-repo
        with:
          rancher-version: ${{ env.RANCHER_VERSION }}
          fallback-repo: ${{ secrets.RANCHER_REPO }}

      - name: Get Qase ID
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        id: get-qase-id
        uses: ./.github/actions/get-qase-id
        with:
          triggered_tag: ${{ github.event.inputs.rancher_version }}
          qase_rc_id: ${{ matrix.qase_rc_id }}
          qase_recurring_id: ${{ matrix.qase_id }}

      - name: Create config.yaml
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        run: |
          cat > config.yaml <<EOF
          rancher:
            host: "${{ env.HOSTNAME_PREFIX }}.${{ secrets.AWS_ROUTE_53_ZONE }}"
            adminPassword: "${{ secrets.RANCHER_ADMIN_PASSWORD }}"
            insecure: true
            cleanup: true
          terraform:
            cni: "${{ secrets.CNI }}"
            defaultClusterRoleForProjectMembers: "true"
            enableNetworkPolicy: false
            provider: "${{ vars.PROVIDER_AMAZON }}"
            privateKeyPath: "${{ secrets.SSH_PRIVATE_KEY_PATH }}"
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            windowsPrivateKeyPath: "${{ secrets.WINDOWS_SSH_PRIVATE_KEY_PATH }}"
            privateRegistries:
              url: "${{ secrets.PRIVATE_REGISTRY_URL }}"
              username: "${{ env.DOCKERHUB_USERNAME }}"
              password: "${{ env.DOCKERHUB_PASSWORD }}"
              insecure: true
              authConfigSecretName: "${{ secrets.AUTH_CONFIG_SECRET_NAME }}"
              mirrorHostname: "${{ secrets.PRIVATE_REGISTRY_MIRROR_HOSTNAME }}"
              mirrorEndpoint: "${{ secrets.PRIVATE_REGISTRY_MIRROR_ENDPOINT }}"
            awsCredentials:
              awsAccessKey: "$AWS_ACCESS_KEY"
              awsSecretKey: "$AWS_SECRET_KEY"
            awsConfig:
              ami: "${{ secrets.AWS_AMI }}"
              awsKeyName: "${{ secrets.SSH_PRIVATE_KEY_NAME }}"
              awsInstanceType: "${{ vars.AWS_INSTANCE_TYPE }}"
              awsVolumeType: "${{ vars.AWS_VOLUME_TYPE }}"
              region: "${{ secrets.AWS_REGION }}"
              awsSecurityGroups: [${{ env.SECURITY_GROUPS }}]
              awsSecurityGroupNames: [${{ env.SECURITY_GROUP_NAMES }}]
              awsSubnetID: "${{ secrets.AWS_SUBNET_ID }}"
              awsVpcID: "${{ secrets.AWS_VPC_ID }}"
              awsZoneLetter: "${{ vars.AWS_ZONE_LETTER }}"
              awsRootSize: ${{ vars.AWS_ROOT_SIZE }}
              awsRoute53Zone: "${{ secrets.AWS_ROUTE_53_ZONE }}"
              awsUser: "${{ secrets.AWS_USER }}"
              sshConnectionType: "${{ vars.SSH_CONNECTION_TYPE }}" 
              timeout: "${{ vars.TIMEOUT }}"
              ipAddressType: "${{ vars.IP_ADDRESS_TYPE }}"
              loadBalancerType: "${{ vars.LOAD_BALANCER_TYPE }}"
              targetType: "${{ vars.TARGET_TYPE }}"
            standalone:
              bootstrapPassword: "${{ secrets.RANCHER_ADMIN_PASSWORD }}"
              certManagerVersion: "${{ vars.CERT_MANAGER_VERSION }}"
              certType: "${{ vars.CERT_TYPE }}"
              chartVersion: "${{ env.RANCHER_CHART_VERSION }}"
              osUser: "${{ secrets.OS_USER }}"
              osGroup: "${{ secrets.OS_GROUP }}"
              rancherAgentImage: "${{ env.RANCHER_AGENT_IMAGE }}"
              rancherChartRepository: "${{ secrets.RANCHER_HELM_CHART_URL }}"
              rancherHostname: "${{ env.HOSTNAME_PREFIX }}.${{ secrets.AWS_ROUTE_53_ZONE }}"
              rancherImage: "${{ secrets.RANCHER_IMAGE }}"
              rancherTagVersion: "${{ env.RANCHER_VERSION }}"
              registryUsername: "${{ secrets.PRIVATE_REGISTRY_USERNAME }}"
              registryPassword: "${{ secrets.PRIVATE_REGISTRY_PASSWORD }}"
              repo: "${{ env.RANCHER_REPO }}"
              rke2Version: "${{ matrix.rke2_version }}"
          terratest:
            pathToRepo: "${{ secrets.PATH_TO_REPO }}"
          EOF

      - name: Export CATTLE_TEST_CONFIG
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        run: echo "CATTLE_TEST_CONFIG=${{ github.workspace }}/config.yaml" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go environment
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: Build Packages
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        run: ./.github/scripts/build-packages.sh

      - name: Install gotestsum
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        run: go install gotest.tools/gotestsum@latest

      - name: Set up Terraform
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ vars.TERRAFORM_VERSION }}"
          terraform_wrapper: false

      - name: Setup Rancher2 Provider if RC is present
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' && contains(env.RANCHER2_PROVIDER_VERSION, '-rc') }}
        run: /home/runner/${{ secrets.PATH_TO_REPO }}/scripts/setup-provider.sh rancher2 v${{ env.RANCHER2_PROVIDER_VERSION }}
        shell: bash

      - name: Run KDM Test Suite
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' }}
        uses: ./.github/actions/run-test-suite
        with:
          package: ${{ env.PACKAGE }}
          path-to-repo: ${{ secrets.PATH_TO_REPO }}
          test-suite: ${{ env.TEST_SUITE }}
          timeout: ${{ env.TIMEOUT }}

      - name: Reporting Results to Qase
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' && always() }}
        uses: ./.github/actions/report-to-qase
        with:
          qase-test-run-id: ${{ matrix.qase_id }}
          qase-automation-token: ${{ secrets.QASE_TOKEN }}

      - name: Refresh AWS credentials
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' && always() }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Revoke Runner IP
        if: ${{ steps.skip-matrix-version.outputs.run == 'true' && always() }}
        uses: ./.github/actions/revoke-runner-ip
        with:
          prefix-list-id: ${{ env.PREFIX_LIST_ID }}
          region: "${{ secrets.AWS_REGION }}"

  report-to-slack:
    needs: kdm-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Reporting Results to Slack
        uses: ./.github/actions/report-to-slack
        with:
          job-status: ${{ needs.kdm-tests.outputs.job-status }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}